[tool.poetry]
name = "rules_pycross_example"
version = "0.1"
description = "rules_pycross"
authors = []

[tool.poetry.dependencies]
python = ">=3.11,<3.13"

ipython = ">=8.17"
moto = {version = "=4.2.7", extras = ["server", "all"]}
SQLAlchemy-Utils = "=0.41.1"
cognitojwt = "*"
python-jose = "=3.3.0"
numpy = "=1.26.1"
Cython = ">=0.29.24,<3.0"
setuptools = "=68.2.2"
wheel = "=0.41.3"
setproctitle = "=1.3.3"
tree-sitter = "=0.20.2"
future = "=0.18.2"
opencv-python = "=4.6.0.66"
keyring = "=23.9.1"
