[project]
name = "rules-pycross-test"
version = "0.1.0"
description = ""
requires-python = ">=3.10, <3.13"
dependencies = [
    "regex",
    # Should NOT be in uv.lock, simulating a user adding
    # numpy and regenerating it with BUILD.bazel.
    # Comment out when regenerating uv.lock.
    "numpy",
]

[project.optional-dependencies]
yaml = [
    "pyyaml",
]

[dependency-groups]
dev = [
    "pytest",
    "ruff",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
